### ISSUE TITLE
Reproduce problem

### ISSUE THREAD

**Issue by xjtushujun** [awslabs/adatune#5]
I tried to run your experiments with your provided hyperparameters, while I found the results are worse than you reported. Can you know the issues?

**Comment by orchidmajumder** [comment]
Can you provide more details? Which experiment you tried, what hyperparameters and how far off are you currently?

**Comment by xjtushujun** [comment]
I have run experiments on CIFAR-10 with ResNet-18 using default parameters, while the learned LR happens to be NaN.

Also, I tried to set \mu as 0.99 or 0.999, and hyper-lr as 1e-6~1e-9. When hyper-lr is large, learned LR would be NaN; and when hyper-lr is large, learned LR would be almost constant.

**Comment by orchidmajumder** [comment]
It depends on the optimizer you are using. For the setup you mentioned, I'd say that for SGD `1e-7` to `1e-9` is a good value for `hyper-lr` and `0.01` is a good initial starting point. For this method, I'd always recommend starting from a lower `initial_lr` because the method can adjust it but if you start from a high value like `0.1` it can often diverge. About the value of `mu`, you can leave that at default or even set to `0.0`. I think I should add this in our documentation.
